import type { GameSnapshot } from '../lib/protocol';

export const gameSnapshot: GameSnapshot = {
  roomId: 'room-1',
  roomCode: 'ABCD2345',
  version: 12,
  handId: 'hand-1',
  turnId: 'turn-1',
  phase: 'playing',
  config: {
    maxPlayers: 4,
    smallBlind: 10,
    bigBlind: 20,
    initialStack: 2000,
    actionTimeoutSeconds: 30,
  },
  players: [
    {
      memberId: 'member-1',
      nickname: '河牌手',
      seat: 0,
      stack: 1880,
      borrowedTotal: 0,
      rankingScore: 1880,
      streetBet: 120,
      committed: 120,
      status: 'active',
      ready: true,
      online: true,
      isHost: true,
      rebuyPending: false,
    },
    {
      memberId: 'member-2',
      nickname: '按钮位',
      seat: 2,
      stack: 1900,
      borrowedTotal: 0,
      rankingScore: 1900,
      streetBet: 100,
      committed: 100,
      status: 'active',
      ready: true,
      online: true,
      isHost: false,
      rebuyPending: false,
    },
  ],
  buttonSeat: 2,
  actingSeat: 0,
  communityCards: ['Ah', '7d', '2c'],
  holeCards: ['As', 'Kh'],
  pots: [{ amount: 220, eligibleMemberIds: ['member-1', 'member-2'] }],
  currentBet: 100,
  legalActions: {
    canFold: true,
    canCheck: false,
    canCall: true,
    canRaise: true,
    canAllIn: true,
    callAmount: 20,
    minRaiseTo: 200,
    maxRaiseTo: 1880,
  },
  deadlineAt: '2030-01-01T00:00:30.000Z',
  serverNow: '2030-01-01T00:00:00.000Z',
  heroMemberId: 'member-1',
  lateJoin: false,
  paused: false,
  closePending: false,
  roomLogs: [],
  completedHands: [],
  fairness: {
    serverCommitment: 'commitment',
    merkleRoot: 'root',
    contributionsReceived: 2,
    contributionsRequired: 2,
    contributionRequired: false,
    auditAvailable: false,
  },
};
